def run(ctx, args):
    import random
    n_cands = args.get("n_candidates", 20)
    max_intervals = args.get("max_intervals", 10)
    seed = args.get("seed", 42)
    random.seed(seed)
    candidates = []
    for i in range(n_cands):
        cand_code = f"import jax.numpy as jnp\nimport optax\n\nclass Hyperparameters:\n    num_intervals: int = {max_intervals}\n    base_learning_rate: float = 0.01\n    num_steps: int = 1000\n    penalty_strength: float = 100.0\n\nclass ErdosOptimizer:\n    def __init__(self, hypers):\n        self.hypers = hypers\n        self.dx = 2.0 / self.hypers.num_intervals\n\n    def _compute_c5_bound(self, h):\n        j = 1.0 - h\n        N = self.hypers.num_intervals\n        h_padded = jnp.pad(h, (0, N))\n        j_padded = jnp.pad(j, (0, N))\n        corr_fft = jnp.fft.fft(h_padded) * jnp.conj(jnp.fft.fft(j_padded))\n        correlation = jnp.fft.ifft(corr_fft).real\n        c5_bound = jnp.max(correlation * self.dx)\n        return float(c5_bound)\n\n    def _get_initialization(self):\n        h = jnp.full({max_intervals}, 0.5)\n        return h\n\n    def _objective_fn(self, latent):\n        h = latent\n        j = 1.0 - h\n        N = self.hypers.num_intervals\n        h_padded = jnp.pad(h, (0, N))\n        j_padded = jnp.pad(j, (0, N))\n        corr_fft = jnp.fft.fft(h_padded) * jnp.conj(jnp.fft.fft(j_padded))\n        correlation = jnp.fft.ifft(corr_fft).real\n        scaled = correlation * self.dx\n        integral_h = jnp.sum(h) * self.dx\n        obj = jnp.max(scaled) + 100.0 * (integral_h - 1.0)**2\n        return obj\n\n    def _optimize_single_run(self):\n        h = self._get_initialization()\n        optimizer = optax.adam(0.01)\n        opt_state = optimizer.init(h)\n        for _ in range(self.hypers.num_steps):\n            loss, grads = jax.value_and_grad(lambda v: self._objective_fn(v))(h)\n            updates, opt_state = optimizer.update(grads, opt_state)\n            h = optax.apply_updates(h, updates)\n        j = 1.0 - h\n        N = self.hypers.num_intervals\n        h_padded = jnp.pad(h, (0, N))\n        j_padded = jnp.pad(j, (0, N))\n        corr_fft = jnp.fft.fft(h_padded) * jnp.conj(jnp.fft.fft(j_padded))\n        correlation = jnp.fft.ifft(corr_fft).real\n        c5_bound = jnp.max(correlation * self.dx)\n        return float(c5_bound)\n\n    def run(self):\n        return self._optimize_single_run()\n"
        candidates.append(("Uniform", cand_code))
    return {"n_generated": n_cands, "candidates": candidates, "note": "Each candidate is a complete code snippet. Replace EVOLVE-BLOCK with it. Then call probe_solution."}
